/run/initialize
/tracking/verbose 0

/gun/energy 40 keV 
/run/beamOn 1000000

/gun/energy 60 keV 
/run/beamOn 1000000

/gun/energy 80 keV 
/run/beamOn 1000000

/gun/energy 100 keV 
/run/beamOn 1000000

/gun/energy 120 keV 
/run/beamOn 1000000

/gun/energy 140 keV 
/run/beamOn 1000000

/gun/energy 160 keV 
/run/beamOn 1000000

/gun/energy 180 keV 
/run/beamOn 1000000

/gun/energy 200 keV 
/run/beamOn 1000000

/gun/energy 220 keV 
/run/beamOn 1000000

/gun/energy 240 keV 
/run/beamOn 1000000

/gun/energy 260 keV 
/run/beamOn 1000000

/gun/energy 280 keV 
/run/beamOn 1000000

/gun/energy 300 keV 
/run/beamOn 1000000

/gun/energy 320 keV 
/run/beamOn 1000000

/gun/energy 340 keV 
/run/beamOn 1000000

/gun/energy 360 keV 
/run/beamOn 1000000

/gun/energy 380 keV 
/run/beamOn 1000000

/gun/energy 400 keV 
/run/beamOn 1000000

/gun/energy 420 keV 
/run/beamOn 1000000

/gun/energy 440 keV 
/run/beamOn 1000000

/gun/energy 460 keV 
/run/beamOn 1000000

/gun/energy 480 keV 
/run/beamOn 1000000

/gun/energy 500 keV 
/run/beamOn 1000000

/gun/energy 520 keV 
/run/beamOn 1000000

/gun/energy 540 keV 
/run/beamOn 1000000

/gun/energy 560 keV 
/run/beamOn 1000000

/gun/energy 580 keV 
/run/beamOn 1000000

/gun/energy 600 keV 
/run/beamOn 1000000

/gun/energy 620 keV 
/run/beamOn 1000000

/gun/energy 640 keV 
/run/beamOn 1000000

/gun/energy 660 keV 
/run/beamOn 1000000

/gun/energy 680 keV 
/run/beamOn 1000000

/gun/energy 700 keV 
/run/beamOn 1000000

/gun/energy 720 keV 
/run/beamOn 1000000

/gun/energy 740 keV 
/run/beamOn 1000000

/gun/energy 760 keV 
/run/beamOn 1000000

/gun/energy 780 keV 
/run/beamOn 1000000

/gun/energy 800 keV 
/run/beamOn 1000000

/gun/energy 820 keV 
/run/beamOn 1000000

/gun/energy 840 keV 
/run/beamOn 1000000

/gun/energy 860 keV 
/run/beamOn 1000000

/gun/energy 880 keV 
/run/beamOn 1000000

/gun/energy 900 keV 
/run/beamOn 1000000

/gun/energy 920 keV 
/run/beamOn 1000000

/gun/energy 940 keV 
/run/beamOn 1000000

/gun/energy 960 keV 
/run/beamOn 1000000

/gun/energy 980 keV 
/run/beamOn 1000000

/gun/energy 1000 keV 
/run/beamOn 1000000

/gun/energy 1020 keV 
/run/beamOn 1000000

/gun/energy 1040 keV 
/run/beamOn 1000000

/gun/energy 1060 keV 
/run/beamOn 1000000

/gun/energy 1080 keV 
/run/beamOn 1000000

/gun/energy 1100 keV 
/run/beamOn 1000000

/gun/energy 1120 keV 
/run/beamOn 1000000

/gun/energy 1140 keV 
/run/beamOn 1000000

/gun/energy 1160 keV 
/run/beamOn 1000000

/gun/energy 1180 keV 
/run/beamOn 1000000

/gun/energy 1200 keV 
/run/beamOn 1000000

/gun/energy 1220 keV 
/run/beamOn 1000000

/gun/energy 1240 keV 
/run/beamOn 1000000

/gun/energy 1260 keV 
/run/beamOn 1000000

/gun/energy 1280 keV 
/run/beamOn 1000000

/gun/energy 1300 keV 
/run/beamOn 1000000

/gun/energy 1320 keV 
/run/beamOn 1000000

/gun/energy 1340 keV 
/run/beamOn 1000000

/gun/energy 1360 keV 
/run/beamOn 1000000

/gun/energy 1380 keV 
/run/beamOn 1000000

/gun/energy 1400 keV 
/run/beamOn 1000000

/gun/energy 1420 keV 
/run/beamOn 1000000

/gun/energy 1440 keV 
/run/beamOn 1000000

/gun/energy 1460 keV 
/run/beamOn 1000000

/gun/energy 1480 keV 
/run/beamOn 1000000

/gun/energy 1500 keV 
/run/beamOn 1000000

/gun/energy 1520 keV 
/run/beamOn 1000000

/gun/energy 1540 keV 
/run/beamOn 1000000

/gun/energy 1560 keV 
/run/beamOn 1000000

/gun/energy 1580 keV 
/run/beamOn 1000000

/gun/energy 1600 keV 
/run/beamOn 1000000

/gun/energy 1620 keV 
/run/beamOn 1000000

/gun/energy 1640 keV 
/run/beamOn 1000000

/gun/energy 1660 keV 
/run/beamOn 1000000

/gun/energy 1680 keV 
/run/beamOn 1000000

/gun/energy 1700 keV 
/run/beamOn 1000000

/gun/energy 1720 keV 
/run/beamOn 1000000

/gun/energy 1740 keV 
/run/beamOn 1000000

/gun/energy 1760 keV 
/run/beamOn 1000000

/gun/energy 1780 keV 
/run/beamOn 1000000

/gun/energy 1800 keV 
/run/beamOn 1000000

/gun/energy 1820 keV 
/run/beamOn 1000000

/gun/energy 1840 keV 
/run/beamOn 1000000

/gun/energy 1860 keV 
/run/beamOn 1000000

/gun/energy 1880 keV 
/run/beamOn 1000000

/gun/energy 1900 keV 
/run/beamOn 1000000

/gun/energy 1920 keV 
/run/beamOn 1000000

/gun/energy 1940 keV 
/run/beamOn 1000000

/gun/energy 1960 keV 
/run/beamOn 1000000

/gun/energy 1980 keV 
/run/beamOn 1000000

/gun/energy 2000 keV 
/run/beamOn 1000000

